### ISSUE TITLE
[QUESTION] Why do some plugins build for VST2 and some don't?

### ISSUE THREAD

**Issue by prg318** [DISTRHO/DISTRHO-Ports#114]
Hi there!  First of all, thanks for an awesome collection of ports of audio plugins to Linux.
I have been wondering:  why are some plugins LV2 only; some plugins are LV2 and VST2; and a few are LV2, VST2, and VST3?
I'm sure there is a technical reason for this, but I'm fairly new to audio plugin development and an explanation would be helpful.

For example, `ports-juce5/Dexed` gets built as a VST2 and LV2, but `ports-juce5/drowaudio-*` only gets built as LV2 units.
To add to my confusion, the upstream `Dexed` project has a CLAP version and a VST3 version.  Is this repo intentionally not building the VST3 version because it's already included in the upstream Dexed project?

It would be awesome to have the `drowaudio` plugins available in VST2 or VST3 format for Linux.  I realize that I can use these plugins in DAWs that do not support LV2 (Like Bitwig Studio) through Carla, but it would be nice to have VST2/3 plugins as well.

One last (somewhat related) question: where is the source code for the TAL plugins upstream?  I'm a huge fan of the TAL plugin suite, but I wasn't aware that any source code for those plugins were made available.  I do see them in other projects, like zynthian-plugins, but I can't see to find any authoritative upstream repo for the TAL plugins - or even a source tarball from the author.

Thanks again for these awesome ports.  Please don't take my questions as criticism - I'd simply like to get a better idea of what's preventing VST builds of some of these awesome ports.  Thanks! Rock on!

**Comment by falkTX** [comment]
any missing VST2 is just a typo/error on my part, didnt even realise that.
for lack of VST3 on some ports, it is because they use JUCE5 which did not have working Linux VST3 support yet.

dexed is a weird case, it was kinda abandoned for a while, reason why it is on the JUCE5 ports, but then got updates regularly. I could move it to JUCE6 (or JUCE7) but that breaks backwards compat with existing projects, at least for now.

on TAL, it is no longer opensource, intentionally by the developer. people "stole" his old GPL code passing it as their own plugins. so he stopped having code available. we keep it for historic reasons

**Comment by prg318** [comment]
Thanks for all the clarification!  That answers all of my questions; much appreciated.

And I'm going to go ahead and close this - it looks like I was just temporarily blind: this repo is in fact building VST2 versions of the drowaudio plugins; not sure how I missed that earlier.  It looks like there is in fact a VST2 version for every LV2 that's built.  Awesome!
