### ISSUE TITLE
Noizemaker - no midi map button

### ISSUE THREAD

**Issue by cloudwheels** [DISTRHO/DISTRHO-Ports#62]
There is no button to open port mapping in noizemaker 3.22 LV2 or VST). Running in Ardour 5.12 on Ubuntu Studio 20.04
I assume this is also how to set the midi channel for the instrument (it plays on all channels).

![image](https://user-images.githubusercontent.com/44451128/97627743-b521c980-1a23-11eb-8d18-bfb74e66062c.png)

**Comment by falkTX** [comment]
This is intentional.
The MIDI learn functionality is incompatible with the current LV2 version, and it is problematic anyway since the host can be automating the parameter while the plugin tries to change at the same too via MIDI CC.
So the feature was removed to reduce sources of conflicts.

MIDI learn is something that needs to be done by the host, not the plugin.

**Comment by cloudwheels** [comment]
@falkTX thanks for the quick response, I now understand the limitation.

My main problem is that the instrument plays back on all midi channels, despite how they are set on the channel in the DAW (Ardour). I don't think I'm missing something about how to set the midi channel in for noizemaker, but if I am, please do let me know!
