### ISSUE TITLE
Proposal for a new Vitalium Logo

### ISSUE THREAD

**Issue by zarp-dev** [DISTRHO/DISTRHO-Ports#67]
I have updated the unfa's Vitalium logo. Changed the colors to be more appropriate, added gradients and a shadow.
I used Inkscape for this! This logo is saved in Inkscape SVG file, all gradients, shadows, etc. are present in this file.

Vitalium logo:
![vitalium-logo-new-2](https://user-images.githubusercontent.com/65812041/109550948-fa90f900-7ae0-11eb-8053-76abb3922f87.png)

Vitalium logo on the black background:
![vitalium-logo-new-2-black](https://user-images.githubusercontent.com/65812041/109550818-d46b5900-7ae0-11eb-818b-5dabba8b98c0.png)

Inkscape SVG file: 
[vitalium-logo-new-2.svg.zip](https://github.com/DISTRHO/DISTRHO-Ports/files/6064099/vitalium-logo-new-2.svg.zip)

**Comment by falkTX** [comment]
Thanks for the attention, but the change of color is intentional.
Using pink would make it look too much like the original, that is not wanted (it is best if it is obvious that vitalium is not vital)

The gradients look cool in big size, but the icon will end up being used in a tiny size, so it is not important at all.

**Comment by IcedQuinn** [comment]
Perhaps this could be closed, since it was rejected?

**Comment by falkTX** [comment]
yes, specially considering we got an svg of unfa's variant
