### ISSUE TITLE
Vitalium: Unsupported openGL Version

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/DISTRHO-Ports#69]
Thanks for your work on linux audio, much appreciated!

With Vitalium, I get the following error:

![screenshot_20210301_195404](https://user-images.githubusercontent.com/7645711/109623521-846eaf80-7b3d-11eb-8b25-6d82f8d51d27.png)

Others are having the same issue with the official Vital binary, and the answers in the forums amount to: upgrade your HW and or SW.

However: 
The Vital fork by @taylordotfish works just fine.

Since I'm using NixOS, wich isolates packages from each other, I thought it might be a dependency issue.
To check, I copied all dependencies from my Vial pkg to my Vitalium pkg, and built again.
No dice. 

Versions:

Vitalium: 2ca1511848d75b26f238855a219168935c282f48
Vial: https://github.com/taylordotfish/vital/commit/c85a58c91c8f118cbd10a88e17f5ebc8c16caa12

I am not yet able to run the official version, because of my OS.
It is possible to patch binaries to work on NixOS, but since I prefer FLOSS, I have not had any practice doing so.

**Comment by falkTX** [comment]
I wonder how @taylordotfish fork can work.
@taylordotfish DId you do any changes for that?

**Comment by magnetophon** [comment]
Seems @tank-trax has the same issue with the upstream version:
https://github.com/mtytel/vital/issues/14#issuecomment-789136943

**Comment by tank-trax** [comment]
the error is with the DISTRHO-Ports build, I forked the Tytel/Vital, made some simple changes to the code and can build VST2, VST3 and Standalone (with JACK support) and they all run without issue, the LV2 loads in jalv but cannot display GUI

(I build using the Makefile from the build folder though) I can also load the .jucer files and tweak to my heart's content and everything works too

I am going to try to hack the DISTRHO-Ports source back into JUCE when I have the time because I like the look of Falk's changes and he likely did needed things that I have no hope of seeing let alone fixing :p

**Comment by falkTX** [comment]
No need to merge back changes I think, as soon enough the distrho-ports version should behave the same as the original.
I am just waiting on Matt to release his custom juce repo

**Comment by falkTX** [comment]
I just realized this is basically the same as #68 so I am closing this ticket. please continue the conversation on #68 thanks
